// load balancer
variable alb_name {}
variable environment {}
variable internal {}
variable load_balancer_type {}
variable alb_security_groups {}
variable public_subnets {}
variable enable_deletion_protection {}
// load balancer target group
variable alb_tg_name {}
variable alb_tg_port {}
variable alb_tg_protocol {}
variable vpc_id {}
variable alb_tg_target_type {}
//variable alb_tg_healthy_threshold {}
//variable alb_tg_interval {}
variable alb_tg_matcher {}
//variable alb_tg_timeout {}
variable alb_tg_path {}
//variable alb_tg_unhealthy_threshold {}
// http listener
variable http_listener_port {}
variable http_listener_protocol {}
variable http_listener_action_type {}
variable http_listener_redirect_port {}
variable http_listener_redirect_protocol {}
variable http_listener_redirect_status_code {}
// https listener
variable https_listener_port {}
variable https_listener_protocol {}
variable alb_tls_cert_arn {}