name: "create a pull request from development to staging"

on:
  push:
    branches:
      - development
  pull_request:

#this action creates a pull request from the development to the staging branch
#but before that runs tests to check if there are no conflicts in the push files

jobs:
  
  stagingPromotion:
    
    name: create pull req
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: staging
      - name: Reset promotion branch
        run: |
          git fetch origin development:development
          git reset --hard development
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: staging-release #creates a temporary branch for the pull request